config:
  inputs: |
    [INPUT]
        Name tail
        Path /var/log/containers/*.log
        multiline.parser docker, cri
        Tag kube.*
        Mem_Buf_Limit 5MB
        Skip_Long_Lines On

  outputs: |
    [OUTPUT]
        Name loki
        Match *
        Host loki.logging.svc.cluster.local
        Port 3100
        Labels job=fluent-bit
        Auto_Kubernetes_Labels on

tolerations:
  - operator: Exists
